config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/index'
  get 'users/top'
  get 'users/edit'
  put 'users/destroy'
  get 'users/delete'
  patch 'users/update'
  get 'users/edit_complete'
  get 'users/complete'

  get '/dietter' => 'home#top'
  root 'home#top'

  resources :users, :except => [:new, :create]
  resources :contacts, only: [:new, :create, :update, :index, :show]
  resources :weights, only: [:index]
  get '/weights/predict' => 'weights#new'
  post '/weights/predict' => 'weights#new'
  get '/weights/calc' => 'weights#calc'
  post '/weights/calc' => 'weights#calc'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :user

    validates :contact_title, presence: true, length: { in: 1..30}
	validates :contact_text, presence: true, length: { in: 2..500}

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :reply, presence: true, format: { with: VALID_EMAIL_REGEX }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, password_length: 6..10

  validates :name, presence: true
  validates :height, presence: true, numericality: true
  validates :latest_weight, presence: true, numericality: true
  validates :ideal_weight, numericality: true
  has_many :contacts

  has_many :weights, dependent: :destroy

  acts_as_paranoid

end

app/models/weight.rb
class Weight < ApplicationRecord
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?


    def after_sign_in_path_for(resource)
      users_top_path # ログイン後に遷移するpathを設定
    end

    def after_sign_out_path_for(resource)
      dietter_path # ログアウト後に遷移するpathを設定
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender, :height, :latest_weight, :ideal_weight, :age, :email, :password, :password_confirmation ])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :gender, :height, :latest_weight, :ideal_weight, :age, :email, :password, :password_confirmation ])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: [:index, :show]

	def new
	  @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
  	@contact.user_id = current_user.id
  	  if @contact.save
        redirect_to users_top_path,notice: "送信しました"
      else
        flash.now[:alert] = "エラー：送信できませんでした"
        render :new
      end
  end

  def index
    @contacts = Contact.all.order(created_at: :desc)
    @user_id = current_user.id
    @contacts = Contact.page(params[:page]).per(10)
  end

  def show
    @contact = Contact.find(params[:id])
    @user_id = current_user.id
  end

  def ensure_correct_user
    if current_user.admin == false
      flash[:notice] = "このアクションは許可されていません"
      redirect_to top_users_path
    end
  end

  private
    def contact_params
  	  params.require(:contact).permit(:contact_title, :contact_text,:reply)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!,except: [:complete]
  before_action :admin_user, only: [:index, :show]

  def index
    @users = User.all
    @search = User.search(params[:q])
    @user = @search.result
    @users = @search.result.page(params[:page]).per(10)
    @user_id = current_user.id
  end

  def show
    @user = User.find(params[:id])
    @user_id = current_user.id
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(current_user.id)
    @user.destroy
    redirect_to users_complete_path
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      weight_change = @user.weights.build(weight_change: @user.latest_weight)
      weight_change.save
      redirect_to users_top_path,notice: "編集が完了しました"
    else
      #updateを失敗すると編集ページに戻る
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

   private
    def user_params
      params.require(:user).permit(:name, :gender, :height, :latest_weight, :ideal_weight, :age, :email)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  before_action :authenticate_user!

	def new
	  @weight = Weight.new
	  @user = current_user
	  weight = @user.latest_weight
  end

  def calc
    @weight = Weight.new
	  @user = current_user
	  weight = @user.latest_weight
	end

  def index
    @weight = Weight.all
    @user = current_user
	  weight = @user.latest_weight


	  #１人のユーザーのweightモデル内のweight_changeカラムの値を全て取得
    weights = Weight.where(:user_id =>@user.id).pluck(:weight_change)
    @categories = Weight.where(:user_id =>@user.id).pluck(:created_at)
    @categories2=@categories.map do |category|
    category.strftime('%m/%d')
    end

    @user = current_user
    ideal = @user.ideal_weight

    @graph = LazyHighCharts::HighChart.new('graph') do |f|
    f.title(text: '')
    f.xAxis(:categories => @categories2)
    f.yAxis(:title => {:text => "kg"})
    f.series(name: '体重', data: weights)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/contacts/index.html.erb
<body class="admin">
  <h1 class="big-letter">お問い合わせ一覧</h1>

  <div class="bigbox">
    <br>
    <div class="table-responsive">
      <table class="table table-hover table-bordered">
          <tr>
            <th class="c1">タイトル</th>
            <th class="c2">内容</th>
           <th class="c3">詳細ページへ</th>
          </tr>
        <% @contacts.each do |contact| %>
          <tr>
	          <td class="c1"><h4 class="dark"><%= contact.contact_title %></h4></td>
	          <td class="c2"><p class="dark"><%= contact.contact_text %></p></td>
            <td class="c3"><h3 class="dark"><%= link_to "詳細", contact_path(contact.id) %></h3></td>
          </tr>
	      <% end %>
      </table>
    </div>
    <div class="pagination">
      <%= paginate @contacts %>
    </div>
  </div>
</body>

app/views/contacts/new.html.erb
<div class="bigbox">
  <span class="big-letter">お問い合わせフォーム</span>
    <%= flash[:alert] %>

      <% if @contact.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <ul>
            <% @contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
      <% end %>
          </ul>
        </div>
    <% end %>

	  <%= form_for (@contact) do |f| %>
      <div class="field-contact">
        <%= f.label :タイトル %><br />
		    <%= f.text_field :contact_title %><br>(30文字以内)
      </div>

      <div class="field-contact">
        <%= f.label :返信用メールアドレス %><br />
        <%= f.email_field :reply, autofocus: true, autocomplete: "email" %>
      </div>

      <div class="field-contact">
	      <%= f.label :内容 %><br />
		      <%= f.text_area :contact_text %><br>(500文字以内)<br>
          <br>
          <%= f.submit "send", class: "btn btn-default btn-lg" %>
      </div>
    <% end %>
</div>

app/views/contacts/show.html.erb
<body class="admin">
  <h1 class="big-letter">お問い合わせ 詳細</h1>
    <div class="bigbox">
      <br>
      <br>
        <div class="table-responsive">
          <table class="table table-hover">
            <thead class="thead-light">
            <tr>
              <th class="c1">タイトル</th>
            </tr>
          </thead>
            <tr>
              <td><h3 class="dark"><%= @contact.contact_title %></h3></td>
            </tr>
            <tr>
              <th class="c2">返信用メールアドレス</th>
            </tr>
            <tr>
              <td><h4 class="dark"><%= @contact.reply %></h4></td>
            </tr>
            <tr>
              <th class="c3">本文</th>
            </tr>
            <tr>
              <td><p class="dark"><%= @contact.contact_text %></p></td>
            </tr>
          </table>
        </div>
    </div>
  </body>

app/views/home/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    </head>
<body class="home">

  <div class="visual">
    <header>
      <h1 class=big> dietter</h1>
      <ul>
		<li class="header">
		  <%= link_to "SIGN IN", new_user_registration_path %>
		</li>
		<li class="header">
		  <%= link_to "LOG IN", new_user_session_path %>
		</li>
	  </ul>
    </header>
    <div>
	  <br>
	</div>
	<div class="go">
	  <%= link_to "GO", users_top_path,class: "start" %>
	</div>
  </div>
  <br>

  <div class="about">
	<h2 class="caption"> HOW TO USE </h2>
	  <h3 class="info">健康的にあなたの体重管理をサポートします。<br>
			カロリーと体重の増減に注目し、<br>
		    自動計算する機能などがあります。</h3>
  </div>
  <br><br><br>

  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="row">
          <div class="col-xs-2">
          </div>
          <div class="col-xs-5">
            <div class=" fas fa-calculator fa-3x">
	            <h3 class="feature">PREDICT YOUR WEIGHT</h3>
	              <h4>1日の摂取カロリーを入力すると、<br>
	    	          あなたの体型や消費エネルギー<br>
	                などから計算される１日あたりの<br>
	                体重の増減が表示されます。</h4>
            </div>
          </div>

          <div class="col-xs-5">
            <div class="box fas fa-tachometer-alt fa-3x">
	            <h3 class="feature">CALCULATE CALORY</h3>
		            <h4>目標体重とダイエットの期間を<br>
			            入力すると、独自の計算により<br>
		              その体重になるための1日の<br>
	                摂取カロリーの目安が表示されます。</h4>
            </div>
          </div>
          <div class="col-xs-2">
          </div>
          <div class="col-xs-5">
	          <div class="box fas fa-weight fa-3x">
	            <h3 class="feature">WEIGHT CHART</h3>
		            <h4>これまでのあなたの体重の変化を<br>
                グラフで一覧表示します。</h4>
	          </div>
          </div>

          <div class="col-xs-5">
            <div class="box fas fa-atom fa-3x">
	            <h3 class="feature">GAIN AND REDUCE WEIGHT</h3>
		            <h4>体重の減量だけでなく、増量の<br>
		                目安にお使いいただくこともできます。</h4>
	          </div>
	        </div>
        </div>
      </div>
    </div>
  </div>
  <br><br><br>

<div class="frame">

  <div class="card">
    <img src="/images/top4.jpg" alt="Avatar" style="width:100%">
    <div class="container">
      <h4><b>PREDICT YOUR WEIGHT</b></h4>
        <p>1日の摂取カロリーを入力すると<br>
	    	あなたの体型や消費エネルギー<br>
	    などから計算される１日あたりの<br>
	    体重の増減が表示されます。</p>
    </div>
  </div>

  <div class="card">
    <img src="/images/top6.jpg" alt="Avatar" style="width:100%">
      <div class="container">
        <h4><b>CALCULATE CALORY</b></h4>
          <p>目標体重とダイエットの期間を<br>
			入力すると、独自の計算により<br>
		    その体重になりための1日の<br>
	        摂取カロリーの目安が表示されます。</p>
      </div>
   </div>

   <div class="card">
    <img src="/images/top7.jpg" alt="Avatar" style="width:100%">
      <div class="container">
        <h4><b>WEIGHT CHART</b></h4>
          <p>これまでの体重の変化を<br>
		グラフで表示します。</p>
      </div>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>dietter</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
      <div id="wrapper">

        <%= yield %>

        <% if user_signed_in? %>
      <footer>

            <div class="flexbox">

              <div class="flexbox-item fas fa-home">
                <%= link_to "ホーム", destroy_user_session_path, method: :delete %>
              </div>

              <div class="flexbox-item fas fa-smile">
                <%= link_to "マイページ", users_top_path %>
              </div>


              <div class="flexbox-item fas fa-user-edit">
                <%= link_to "プロフィール編集", edit_user_path(current_user.id) %>
              </div>

              <div class="flexbox-item fas fa-user-edit">
                <%= link_to "お問い合わせ", new_contact_path %>
              </div>

              <div class="flexbox-item fas fa-sign-out-alt">
               <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </div>

            </div>
        <% else %>
          <p class="fotter-text">CopyRight 2019 dietter All right reserved.</p>
        <% end %>
      </footer>
      </div>
    </body>
  </html>

app/views/users/complete.html.erb
<div class="bigbox">
  	<h1 class="complete">Thank you! We deleted your account.</h1>
    <h4>アカウント削除・退会処理が完了いたしました。<br>
       ご利用ありがとうございました。</h4>
    <hr>
    <div class="line">
      <%= link_to "TOPへ戻る", destroy_user_session_path, method: :delete, class: "btn btn-default btn-lg" %>
    </div>
  </div>

app/views/users/delete.html.erb
<div class="bigbox">
  <span class="big-letter">アカウント削除</span>
    <br>
    <br>
    <ul>
    <li class="dark"><i class="fas fa-chevron-circle-right"></i> 複数の機能が使用できなくなります。</li><br>
    <li class="dark"><i class="fas fa-chevron-circle-right"></i> 保存されている全てのデータが削除されます。</li><br>
    <li class="dark"><i class="fas fa-chevron-circle-right"></i> 再登録しても以前のデータは引き継ぎができません。</li>
  </ul>
　　　<br><br>
    <h4 class="dark">よろしいですか？</h4>
    <div class="line">
      <%= link_to 'やっぱり削除しない', users_top_path,class: "btn btn-default btn-lg" %>
    </div>

      <hr>
    <div class="line">
      <%= link_to 'アカウント削除・退会', users_complete_path, method: :delete, class: "btn btn-default btn-lg" %>
    </div>
</div>

app/views/users/edit.html.erb
<div class="bigbox">
  <span class="big-letter">プロフィール編集</span>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

　<%=  form_for(@user) do |f| %>
    <div class="field">
      <%= f.label :名前（ニックネーム可） %><br />
      <%= f.text_field :name, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :性別 %><br />
      <%= f.select :gender, [["女性", "1"], ["男性", "2"]] %>
    </div>

　  <div class="field">
      <%= f.label :身長 %><br />
      <%= f.text_field :height, :placeholder => "  160.0", autofocus: true %><span> cm</span>
    </div>

    <div class="field">
      <%= f.label :体重 %><br />
      <%= f.text_field :latest_weight, :placeholder => "  50.0", autofocus: true %><span> kg</span>
    </div>

    <div class="field">
      <%= f.label :目標体重 %><br />
      <%= f.text_field :ideal_weight, :placeholder => "  48.0", autofocus: true %><span> kg</span>
    </div>

    <div class="field">
      <%= f.label :年代 %><br />
      <%= f.select :age, [["10代", "1"], ["20代", "2"], ["30代", "3"], ["40代", "4"], ["50代", "5"], ["60代", "6"]] %>
    </div>

    <div class="field">
      <%= f.label :メールアドレス %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div><br><br>

    <% if @user.weights.exists? %>
        <% if @user.weights.last.updated_at == Date.today %>
          <div class="actions">
            <%= f.submit "更新" %>
         </div>
        <% else %>
          <div class="actions">
          </div>
          <div class="alert alert-danger" role="alert"><strong>※ 注意</strong> - - 体重の更新は１日１回までです　- - </div>
        <% end %>

    <% else %>
      <div class="actions">
        <%= f.submit "更新" %>
      </div>
    <% end %><br>

    <%= link_to "戻る", users_top_path %> |

    <%= link_to "アカウントを削除する", users_delete_path(current_user.id) %>
  <% end %>
</div>

app/views/users/index.html.erb
<body class="admin">
  <h1 class="big-letter">ユーザー一覧</h1>
    <div class="bigbox">

      <%= search_form_for @search do |f| %>
          <div class="form-group">
            <%= f.text_field :name_cont, class: "form-control" %>
            <button type="submit" class="button1">
              <i class="fas fa-search"></i>検索
            </button>
     <% end %>

      <br>
      <br>
      <div class="table-responsive">
        <table class="table table-hover table-bordered">
          <tr><th class="name">名前</th>
          <th>登録日時</th>
          <th>詳細ページへ</th></tr>

            <% @users.each do |user| %>
              <tr><td class="name"><h4 class="name-style"><%= user.name %></h4></td>
              <td><h4 class="dark"><%= user.created_at.strftime('%Y/%m/%d %H:%M') %></h4></td>
              <td><h4 class="dark"><%= link_to "詳細", user_path(user.id) %></h4></td>
              </tr>
            <% end %>
        </table>
      </div>

    <div class="pagination">
      <%= paginate @users %>
    </div>
  </div>
</div>
</body>

app/views/users/show.html.erb
<body class="admin">
<h1 class="big-letter">ユーザー 詳細</h1>
  <div class="bigbox">
    <br>
    <br>
    <br>
      <div class="table-responsive">
        <table class="table table-hover table-bordered detail">
		    <tr>
			  <th>名前</th>
		      <td><h3 class="dark"><%= @user.name %></h3></td>
		    </tr>
	        <tr>
	  	      <th>性別</th>
	  	      <td><p class="dark"><%= @user.gender %>&nbsp;&nbsp;(1=女性,2=男性)</p></td>
	        </tr>
	        <tr>
              <th>身長</th>
              <td><p class="dark"><%= @user.height %>&nbsp;cm</p></td>
	        </tr>
	        <tr>
	          <th>体重</th>
	          <td><p class="dark"><%= @user.latest_weight %>&nbsp;kg</p></td>
	        </tr>
	        <tr>
	  	      <th>目標体重</th>
	  	      <td><p class="dark"><%= @user.ideal_weight %>&nbsp;kg</p></td>
	        </tr>
	        <tr>
              <th>年代</th>
              <td><p class="dark"><%= @user.age %>0代</p></td>
	        </tr>
	        <tr>
	  	      <th>メールアドレス</th>
	  	      <td><p class="dark"><h4 class="name-style"><%= @user.email %></h4></p></td>
	        </tr>
        </table>
      </div>
      <%= link_to "削除", users_index_path, class: "btn  btn-lg btn-danger user_#{@user.id}", method: :delete, "data-confirm" => "本当に削除しますか？" %>
  </div>
</body>

app/views/users/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag "application" %>
  <link href="/stylesheets/style.css" media="screen" rel="stylesheet" type="text/css" />
<body>
<div class="bigbox">
<span class="big-letter">MY PAGE</span>

<% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong> Great! </strong>-- You did it succesfully --
    </div>
  <% end %>
  <div class="space">
    </div>
    <br><br>
    <div class="icon">MENU
        <ul class="menu">

    <li class="spread">
          <a class="unit" href="/weights/calc">カロリー計算</a>
    </li>

    <li class="spread">
          <a class="unit" href="/weights">体重グラフ</a>
    </li>

    <li class="spread">
          <a class="unit" href="/users/edit"><i class="fas fa-wrench"></i>&nbsp;設定</a>
    </li>

    <li class="spread">
          <a class="unit" href="#"><span class="btn-heart">&hearts;</span></a>
    </li>

    <li class="spread">
          <a class="unit" href="/weights/predict">体重予測</a>
    </li>


  </ul>
  </div>
</div>
<% if current_user.admin == true %>
  <li class="header">
    <br><br>
    <%= link_to "ユーザー一覧", users_path  %><br>
    <%= link_to "問い合わせ一覧", contacts_path  %>
  </li>
  <% end %>
</body>
</head>

app/views/weights/calc.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="style.scss">
</head>

<body class="home">
  <div class="img">
　　<h1 class="effect"><small>目標実現のためのカロリー計算</small>
    <% time = Time.now %>
      <%= time.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[Time.now.wday]})") %><br>
      体重&nbsp;<%= @user.latest_weight %> kg<br>
       BMI&nbsp;<%= (@user.latest_weight / ( @user.height / 100.0 ) ** 2).round(2) %>
  </small></h1>
</div>
<br>

      <form>
        <label for="textForm1">目標体重 </label>
        <input type="text" id="ideal_weight"><span>kg</span><br><br><br>

        <label for="textForm2">期間 </label>
        <input type="text" id="term"><span>日</span><br>

        <button id="button">計算</button>
      </form>

      <form>
        <label for="resultForm"><h3>1日の摂取カロリーが</h3></label>
        <input type="text" id="resultForm"><span>cal</span><h3> 程度で実現可能</h3>
      </form>

    <script>
      // ボタンの要素を取得
      var button = document.getElementById("button");
      // ボタンをクリックした時の処理
      button.addEventListener("click", function(e) {
       e.preventDefault();
      // 2つの入力フォームの値を取得
      var textForm1 = document.getElementById("ideal_weight").value;
      var textForm2 = document.getElementById("term").value;
      var weight = <%= raw @user.latest_weight.to_json %>
      // console.log(weight + "json");
      weight = Number(weight);
      var burncalory = (weight * 23.6) /0.6;
      console.log(calory);
      // 2つの数値を足す
      var calory = (weight - parseFloat(textForm1)) / parseFloat(textForm2) * 7000;
      var idealcalory = burncalory - calory;
      // 計算の結果を別の入力フォームに表示
      var resultForm = document.getElementById("resultForm");
      resultForm.value = idealcalory;
      // 小数点以下を切り捨て
      resultForm.value = Math.floor(resultForm.value);
      //800cal以下は表示しないように設定
      var borderValue = 800;
        if (idealcalory < borderValue) {
          alert("注意：過度な増量・減量は健康を害する恐れがあるので表示できません。");
          resultForm.value = "";
        }
　　　　});
　　　</script>

      <div class="alert alert-danger" role="alert">
        <strong>注意！
        </strong> - 結果には個人差があります。こちらの数値は計算上で得られる結果であり、実際の体重変化とは差があります。体重管理の目安としてお使いください。
      </div>
    </body>
　　</html>

app/views/weights/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
  </head>
</head>

<body class="home">
  <div class="img">
  <h1 class="effect"><small>体重変化：グラフ</small>
    <% time = Time.now # Thu Dec 24 00:00:00 +0900 2011  %>
    <%= time.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[Time.now.wday]})") %><br>
      体重&nbsp;<%= @user.latest_weight %> kg<br>
      BMI&nbsp;<%= (@user.latest_weight / ( @user.height / 100.0 ) ** 2).round(2) %></small></h1>
  </div>
  <main>
    <h4 class="dark">現在までの体重変化 </h4><br>
    <%= high_chart("sample", @graph) %>
  </main>
</body>
</html>

app/views/weights/new.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="style.scss">
</head>

<body class="home">
  <div class="img">
  <h1 class="effect"><small>体重予測</small>
    <% time = Time.now %>
      <%= time.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[Time.now.wday]})") %><br>
      体重&nbsp;<%= @user.latest_weight %> kg<br>
       BMI&nbsp;<%= (@user.latest_weight / ( @user.height / 100.0 ) ** 2).round(2) %>
  </small></h1>
</div>
    <h3 class="dark">１日の摂取カロリーを入力してください </h3><br>

    <script>

       // ボタンの要素を取得
      var button = document.getElementById("button");

      // ボタンをクリックした時の処理
      button.addEventListener("click", function(e) {

      e.preventDefault();

      // 2つの入力フォームの値を取得
      var textForm1 = document.getElementById("textForm1").value;
      var textForm2 = document.getElementById("textForm2").value;

      // 2つの数値を足す
      var sum = parseInt(textForm1, 10) + parseFloat(textForm2, 10);

      // 足し算の結果を別の入力フォームに表示
      var resultForm = document.getElementById("resultForm");
      resultForm.value = sum;
      });

    </script>

      <form>
        <label for="textForm">合計</label>
        <input type="text" id="textForm"><span>cal</span><br>
        <button id="button">計算</button>
      </form>
      <br>

      <form>
        <label for="resultForm">予想体重</label>
        <input type="text" id="resultForm"><span>kg</span>
      </form>
      <br>

<div class="alert alert-danger" role="alert">
      <strong>注意！
     </strong> - 結果には個人差があります。こちらの数値は計算上で得られる結果であり、実際の体重変化とは差があります。体重管理の目安としてお使いください。
    </div>
    <script>

      // ボタンの要素を取得
      var button = document.getElementById("button");

      // ボタンをクリックした時の処理
      button.addEventListener("click", function(e) {

      e.preventDefault();

      // 入力フォームの値を取得
      var textForm = document.getElementById("textForm").value;
      var weight = <%= raw @user.latest_weight.to_json %>
      // console.log(weight + "json");
      weight = Number(weight);
      var burncalory = (weight * 23.6) /0.6;
      console.log(burncalory);

      // 数値を四則計算
  　  var total = parseFloat(textForm, 10) - parseFloat(burncalory, 10);

      // 取得した値を別の入力フォームに表示
      var resultForm = document.getElementById("resultForm");
      //1kg=約7000calなので
      resultForm.value = total /7000;
      // 小数点第3位を四捨五入
      resultForm.value = Math.round(resultForm.value *100) /100;

      //時間があれば今の体重に取得した値を足したものを表示させる。
      //運動量と年代から計算式をif文で作り式を複雑化する。
      });

    </script>

</body>
</html>